## Import libraries

In [1]:
import tensorflow as tf 
import matplotlib.pyplot as plt 
import pandas as pd 
import seaborn as sns 

## Data loading and Image Preprocessing

In [2]:
training_set = tf.keras.utils.image_dataset_from_directory(
    './Plant_Disease_Dataset/train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 70295 files belonging to 38 classes.


In [3]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    './Plant_Disease_Dataset/valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 17572 files belonging to 38 classes.


## Building the CNN Model

In [4]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [5]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[139. 127. 139.]
   [166. 154. 166.]
   [117. 105. 117.]
   ...
   [ 53.  30.  40.]
   [ 53.  30.  40.]
   [ 54.  31.  41.]]

  [[153. 141. 153.]
   [134. 122. 134.]
   [132. 120. 132.]
   ...
   [ 53.  30.  40.]
   [ 53.  30.  40.]
   [ 53.  30.  40.]]

  [[113. 101. 113.]
   [112. 100. 112.]
   [131. 119. 131.]
   ...
   [ 52.  29.  39.]
   [ 53.  30.  40.]
   [ 53.  30.  40.]]

  ...

  [[158. 150. 163.]
   [161. 153. 166.]
   [165. 157. 170.]
   ...
   [127. 114. 132.]
   [126. 113. 131.]
   [125. 112. 130.]]

  [[160. 152. 165.]
   [162. 154. 167.]
   [165. 157. 170.]
   ...
   [128. 115. 133.]
   [128. 115. 133.]
   [128. 115. 133.]]

  [[161. 153. 166.]
   [161. 153. 166.]
   [161. 153. 166.]
   ...
   [124. 111. 129.]
   [125. 112. 130.]
   [126. 113. 131.]]]


 [[[156. 138. 136.]
   [157. 139. 137.]
   [114.  96.  94.]
   ...
   [166. 152. 149.]
   [118. 104. 101.]
   [174. 160. 157.]]

  [[112.  94.  92.]
   [142. 124. 122.]
   [140. 122. 120.]
   ...
   [116. 1

In [6]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from tensorflow.keras.models import Sequential

In [7]:
cnn = Sequential()

In [8]:
cnn.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[256,256,3]))
cnn.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
cnn.add(MaxPool2D(pool_size=2,strides=2))

C:\Users\PC\LocalRepo\project\.venv\lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
cnn.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
cnn.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
cnn.add(MaxPool2D(pool_size=2,strides=2))

In [10]:
cnn.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
cnn.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
cnn.add(MaxPool2D(pool_size=2,strides=2))

In [11]:
cnn.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
cnn.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
cnn.add(MaxPool2D(pool_size=2,strides=2))

In [12]:
cnn.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
cnn.add(Conv2D(filters=512,kernel_size=3,activation='relu'))
cnn.add(MaxPool2D(pool_size=2,strides=2))

In [13]:
cnn.add(Flatten())
cnn.add(Dense(units=512, activation='relu'))
cnn.add(Dropout(0.5))
cnn.add(Dense(units=38, activation='softmax'))

In [14]:
cnn.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001), # Standard string 'adam' is 0.001 (too high for this depth)
    loss='categorical_crossentropy',
    metrics=['accuracy']
)
cnn.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 256, 256, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 254, 254, 32)        │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 127, 127, 32)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 127, 127, 64)        │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 125, 125, 64)        │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 62, 62, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_4 (Conv2D)                    │ (None, 62, 62, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_5 (Conv2D)                    │ (None, 60, 60, 128)         │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 30, 30, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_6 (Conv2D)                    │ (None, 30, 30, 256)         │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_7 (Conv2D)                    │ (None, 28, 28, 256)         │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 14, 14, 256)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_8 (Conv2D)                    │ (None, 14, 14, 512)         │       1,180,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_9 (Conv2D)                    │ (None, 12, 12, 512)         │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (None, 6, 6, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 18432)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 512)                 │       9,437,696 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 512)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 38)                  │          19,494 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 14,169,414 (54.05 MB)

 Trainable params: 14,169,414 (54.05 MB)

 Non-trainable params: 0 (0.00 B)

## Model Training and Evaluation

In [15]:
training = cnn.fit(x=training_set, validation_data=validation_set, epochs=20)

Epoch 1/20
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2133s 970ms/step - accuracy: 0.6140 - loss: 1.3539 - val_accuracy: 0.8541 - val_loss: 0.4672
Epoch 2/20
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1979s 901ms/step - accuracy: 0.8682 - loss: 0.4280 - val_accuracy: 0.9302 - val_loss: 0.2155
Epoch 3/20
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1886s 858ms/step - accuracy: 0.9238 - loss: 0.2402 - val_accuracy: 0.9409 - val_loss: 0.1841
Epoch 4/20
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1888s 860ms/step - accuracy: 0.9490 - loss: 0.1592 - val_accuracy: 0.9456 - val_loss: 0.1699
Epoch 5/20
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1888s 859ms/step - accuracy: 0.9622 - loss: 0.1193 - val_accuracy: 0.9562 - val_loss: 0.1403
Epoch 6/20
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1886s 859ms/step - accuracy: 0.9712 - loss: 0.0881 - val_accuracy: 0.9507 - val_loss: 0.1845
Epoch 7/20
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1885s 858ms/step - accuracy: 0.9756 - loss: 0.0768 - val_accuracy: 0.9744 - val_loss: 0.0848
Epoch 8/20
1631/2197 ━━━━━━━━━━━━━━━━━━━━ 7:32 800ms/st

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1884s 858ms/step - accuracy: 0.9851 - loss: 0.0489 - val_accuracy: 0.9689 - val_loss: 0.0997
Epoch 11/20
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1885s 858ms/step - accuracy: 0.9868 - loss: 0.0439 - val_accuracy: 0.9441 - val_loss: 0.1930
Epoch 12/20
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1883s 857ms/step - accuracy: 0.9872 - loss: 0.0396 - val_accuracy: 0.9751 - val_loss: 0.0902
Epoch 13/20
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1885s 858ms/step - accuracy: 0.9888 - loss: 0.0358 - val_accuracy: 0.9731 - val_loss: 0.1135
Epoch 14/20
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2094s 953ms/step - accuracy: 0.9905 - loss: 0.0317 - val_accuracy: 0.9686 - val_loss: 0.1164
Epoch 15/20
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2175s 990ms/step - accuracy: 0.9911 - loss: 0.0304 - val_accuracy: 0.9726 - val_loss: 0.1081
Epoch 16/20
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2288s 1s/step - accuracy: 0.9918 - loss: 0.0279 - val_accuracy: 0.9762 - val_loss: 0.0921
Epoch 17/20
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2170s 988ms/step - a

In [16]:
train_loss,train_acc = cnn.evaluate(training_set)
print(train_loss,train_acc)

2197/2197 ━━━━━━━━━━━━━━━━━━━━ 575s 262ms/step - accuracy: 0.9971 - loss: 0.0090
0.00895649567246437 0.997140645980835


In [17]:
val_loss,val_acc = cnn.evaluate(validation_set)
print(val_loss,val_acc)

550/550 ━━━━━━━━━━━━━━━━━━━━ 144s 262ms/step - accuracy: 0.9774 - loss: 0.0890
0.08904984593391418 0.9773503541946411


## Saving Model

In [18]:
cnn.save("trained_model.keras")

In [20]:
training.history

{'accuracy': [0.6139839291572571,
  0.8681840896606445,
  0.923835277557373,
  0.9489864110946655,
  0.9621737003326416,
  0.9711928367614746,
  0.9756312966346741,
  0.9788320660591125,
  0.9828437566757202,
  0.9850772023200989,
  0.9867557883262634,
  0.9872394800186157,
  0.9887616634368896,
  0.9905256628990173,
  0.9910804629325867,
  0.9917917251586914,
  0.9916210174560547,
  0.9927021861076355,
  0.9918344020843506,
  0.9937264323234558],
 'loss': [1.353872537612915,
  0.42802485823631287,
  0.24016471207141876,
  0.15924574434757233,
  0.11925505846738815,
  0.08806827664375305,
  0.07681256532669067,
  0.06620516628026962,
  0.05465520918369293,
  0.04893213137984276,
  0.04385041072964668,
  0.03960909694433212,
  0.035834647715091705,
  0.031678035855293274,
  0.03043406456708908,
  0.027927979826927185,
  0.027450846508145332,
  0.023247109726071358,
  0.026254013180732727,
  0.02159011736512184],
 'val_accuracy': [0.854142963886261,
  0.930229902267456,
  0.9408718347549

In [22]:
import json
with open("training_hist.json", "w") as f:
    json.dump(training.history, f)

In [24]:
training.history['val_accuracy']

[0.854142963886261,
 0.930229902267456,
 0.9408718347549438,
 0.9455952644348145,
 0.9561802744865417,
 0.9506601691246033,
 0.9744479656219482,
 0.9631800651550293,
 0.9596517086029053,
 0.9688709378242493,
 0.9440587162971497,
 0.9751309156417847,
 0.9731391072273254,
 0.968643307685852,
 0.9726269245147705,
 0.9761552214622498,
 0.9786023497581482,
 0.976496696472168,
 0.9769519567489624,
 0.9773503541946411]